# _config.yml
title: My Jekyll Site
description: "A simple site using the Cayman theme."
url: "https://skarthiky.github.io"  # Replace with your GitHub Pages URL

remote_theme: "pages-themes/cayman@v0.1.0"  # Use pages-themes/cayman instead of just cayman
theme: "cayman"  # You can optionally leave this, but it's fine to specify
# Site-specific configurations
baseurl: ""  # Leave empty unless you're using a subfolder
permalink: /:year/:month/:day/:title/  # This is for blog post URL structure

# Optional: you can add other fields like social media links, navigation, etc.
